name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/run-tests.yml

  build:
    name: Run build
    uses: ./.github/workflows/run-build.yml

  docs:
    name: Generate Crate Docs
    uses: ./.github/workflows/docs.yml

  msrv:
    name: Check MSRV
    strategy:
      matrix:
        toolchain: ["1.83.0"]
        target: ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]
    uses: ./.github/workflows/check-msrv.yml
    with:
      toolchain: ${{ matrix.toolchain }}
      target: ${{ matrix.target }}

  nix-flake:
    name: Nix Flake
    uses: ./.github/workflows/nix-flake.yml
